name: Deploy Gmonad.cc 

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  

      - name: Install dependencies
        run: npm install

      - name: Build VitePress site
        run: |
          npm run docs:build 

      - name: Deploy to Remote Server via SSH
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}  
          username: ${{ secrets.SERVER_USERNAME }}  
          key: ${{ secrets.SERVER_SSH_KEY }} 
          source: ".vitepress/dist"  
          target: "/var/www/"  
